### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by lukaseder**
Added a blog post to the list

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks, @lukaseder! Out of curiousity, have you compared this approach to Compile Testing? We also had built our own testing infra for MapStruct, but I wouldn't bother doing this again now that this library exists.

**Comment by lukaseder** [comment]
To be honest, I hadn't explored all the options. The in-memory compilation API already existed in jOOR. Adding processing capabilities was easy. Compile Testing (by google) is probably more thorough

**Comment by gunnarmorling** [comment]
Gotcha. Used Compile Testing for my latest experiment Deptective and it worked well. Not worth though migrating existing tests.

**Comment by vegegoku** [comment]
Testing if the code compiles or not might proven to be a good thing, but should always write tests that tests the generated code and make sure it behave as expected and this in general might save you from over testing the processor.

**Comment by gunnarmorling** [comment]
Yes, that's what we do for MapStruct, too. Running the generated code and
assert it does the expected thing.

>

**Comment by filiphr** [comment]
I like the way we are doing it in MapStruct as we can assert the generated file and run the generated class in the same test. Not sure if you can do this with Compile Testing.

**Pull request merged**
