### PR TITLE
Add Project Lombok

### PR DESCRIPTION
**Pull request by mdeinum**

### CODE REVIEW

**Comment by vegegoku** [comment]
@mdeinum Lombok is not an annotation processor, it does not follow the specification and does not use the API, they just make use of the annotation processing compilation phase to some internal compiler APIs, it should not be considered an annotation processor sample.

http://notatube.blogspot.com/2010/11/project-lombok-trick-explained.html

**Comment by gunnarmorling** [comment]
Ha, yeah, I was waiting for someone to suggest Lombok. In general I also dislike the fact that it violates the boundaries of the JSR 269 API. But then of course it's a popular tool and omitting it seems a bit weird either. Perhaps indeed under "Related Concepts"?

**Comment by vegegoku** [comment]
It is not about like and dislike, lombok is used by many people in many projects and proven to be useful for them, but can we list as an annotation processor when it is not?! Isnt this a false piece of information?!

**Comment by gunnarmorling** [comment]
Well, I think technically it is an AP, it just happens to cast the public interface types into javac-specific implementations. I'll add it to the "Related..." sections. The javac plug-in API is already there, so it seems a git place.

**Comment by gunnarmorling** [comment]
Applied; thanks, @mdeinum!

**Pull request closed without merging**
